# Christian Quintero
# February 14, 2026
# Collatz Conjecture Algorithm
# COSC 4348 - Systems Programming - Assignment 2
#
# This is the makefile for Collatz_Quintero.c
# It will create the program and clean up the directory when done

Collatz_Quintero:
	gcc -o Collatz_Quintero Collatz_Quintero.c

# remove the executable and all object files and data files
clean:
	rm -f Collatz_Quintero *.o *.dat